### ISSUE TITLE
This is a test

### ISSUE THREAD

**Issue by FurrehIzzy** [ohno-boko/MiddleCraft#22]
# Minecraft Server Issue :beetle:
**A clear and concise description of what the issue you ran into was.  Please limit this to technical, connectivity, and gameplay issues. There are other issue trackers for community or stream troubles. Areas in *italics* are meant to be replaced with your text. Thank you!**

### Summary of your issue
I was unable to connect to the server, even though I tried over 30 dozen times to re-attempt connection to the server.

### Additional Details

**Version**
  * [x] Java
  * [ ] Bedrock

**Error code you received**
[io.netty.channel.AbstractChannel$AnnotatedConnectException:  Connection timed out: no further information:]
  * [ ] No error, client crashed

**Access Point**
  * Device: [Windows Computer]
  * OS:  [Windows 10]
  * Client Version:  [1.6.3]
  * Mod version: [-- --]
      * [x] Not a modded client
  * Other comments:  I used IP mc.ohnoboko.com:20505 to try and connect to the server.

# Final Comments
**Please attach any photos, or list anything additional you may deem important to resolving the issue.  Thank you, and we will get back to you as soon as we can.**

**Comment by FurrehIzzy** [comment]
wow sounds like u succ

**Comment by ninetail2** [comment]
Looks cool.


> 
> 
> wow sounds like u succ

Yeah, I succ your dicc.

**Comment by hellot1m** [comment]
Does this person even know how to use a computer. i bet they spent $1000 on their computer just to watch porn.
